[package]
name = "adventOfCode"
version = "0.1.0"
authors = ["Sebastian DÃ¤deby <s.dadeby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "day_01"
path = "src/day1/day1.rs"